name: hygeiene

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  ensure-mock-gen:
    # Generation assurance test workflow
    # (e.g. no uncovered diffs in go-mocks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: Mock diff check
        run: make go-gen-mocks && git diff --exit-code

  golangci:
    # Linting job
    # https://github.com/golangci/golangci-lint-action
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.52.1